export const UserConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',
    CLOSE_LOGIN_ALERT: "CLOSE_LOGIN_ALERT",
    KEY_EXCHANGE_REQUEST: "KEY_EXCHANGE_REQUEST",
    KEY_EXCHANGE_SUCCESS: "KEY_EXCHANGE_SUCCESS",
    KEY_EXCHANGE_FAILURE: "KEY_EXCHANGE_FAILURE"
    
};